### ISSUE TITLE
Notice: Array to string conversion

### ISSUE THREAD

**Issue by Avtonom** [mathielen/import-engine#9]
Notice: Array to string conversion
in 'name' => $this->callable.'',

```php
Exception trace:
 () at /vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Storage/ServiceStorage.php:78
 Symfony\Component\Debug\ErrorHandler->handleError() at/vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Storage/ServiceStorage.php:80

 Mathielen\ImportEngine\Storage\ServiceStorage->info() at /vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Import/ImportBuilder.php:120

 Mathielen\ImportEngine\Import\ImportBuilder->build() at /vendor/mathielen/import-engine/src/Mathielen/ImportEngine/Import/ImportBuilder.php:103
```

app/config/config.yml

```yml
mathielen_import_engine:
    storageprovider:
        default:
            type: service
            services:
                my_service: ~
    importers:
        minimum_importer:
            target:
                type: file
                uri: "@='%kernel.root_dir%/../output_'~date('Y-m-d')~'.csv'"
                format: csv
```

```
$ php ./app/console importengine:import my_service.findAll -i minimum_importer -vvv
```
